### PR TITLE
Added tests for username and fixes username issue

### LINKED ISSUE #170: Username not being added to kitchen state when running test kitchen
# Version:

master code (1.3.0)

# Environment:

Windows 10
ChefDK version: 4.11.0
Chef Infra Client version: 15.14.0
Chef InSpec version: 4.22.22
Test Kitchen version: 2.7.1
Foodcritic version: 16.3.0
Cookstyle version: 5.23.0

# Scenario:

Username not being added to state

# Steps to Reproduce:

- Run kitchen command that will spin up a VM 
- Inspect the kitchen state file

# Expected Result:

```yaml
---
<...>
username: azure
<...>
```

# Actual Result:

```yaml
---
<...>
username:
<...>
```

Let me know if theres anything I can do, Happy to help 😄

### PR DESCRIPTION
**Pull request by ElementalDev**
### Description

Fixes the username issue and adds tests to assess ```:username``` in the config

### Issues Resolved

#170 Issue with username

### Check List

- [x] New functionality includes tests
- [x] All tests pass
- [x] PR title is a worthy inclusion in the CHANGELOG

### CODE REVIEW

**Comment by StylusEaterChef** [comment]
@ElementalDev thank you for the addition. I noticed we're now using a symbol for adminUsername but not adminPassword. Seems like we might want to be consistent with that so would you mind changing that to match your change, add another test and confirm a test `kitchen create/test` works for you?

**Comment by ElementalDev** [comment]
Well, see now this is a strange one. When I changed both, the Password stopped being filled into the state.

**Comment by ElementalDev** [comment]
I might have sorted that, ill rerun and let you know

**Comment by ElementalDev** [comment]
Thats all sorted and works as expected

**Review by StylusEaterChef — APPROVED** [review]
Testing worked for me. Nice work. Thank you.

**Review by devopsdina — APPROVED** [review]

**Comment by StylusEaterChef** [comment]
Thank you.

**Pull request merged**
